### ISSUE TITLE
[Bug]: Can`t run the Basic 1.1 Serverpack

### ISSUE THREAD

**Issue by Rezondes** [dr3ams/Roguelike-Adventures-and-Dungeons-2#219] opened 2023-03-07 20:34 UTC
### General Info

- [x] I didn't added any mods
- [ ] I can reproduce this issue consistently in single-player
- [x] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [x] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

Linux Debian

### Modpack version

1.1

### Describe your issue

I can't start the server with the default files.

### Steps to reproduce the issue

1. Download Serverfiles
2. Unpack Zip
3. Run the Bat-File

### Additional Information

Crashreport:
[crash-2023-03-07_20.37.47-fml.txt](https://github.com/dr3ams/Roguelike-Adventures-and-Dungeons-2/files/10913767/crash-2023-03-07_20.37.47-fml.txt)

**Comment by KimoKat** [comment] 2023-03-07 21:00
Similar issue; server files sent to BisectHosting do not match up with the client versions for many of the mods. Had to backup to 1.0a until this is resolved. 

Using BisectHosting for the server.
Myself and my friends use Overwolf (CurseForge's App) to download the pack. The singleplayer pack seems file and working, the server files are missing some mods though.

**Comment by ImCoolio** [comment] 2023-03-08 07:51
+1 Happening to me and my friends as well.

**Comment by Redeye123** [comment] 2023-03-08 22:06
looks like java 11 "Java Version: 11.0.18, Debian" try java 8 since its 1.16.5

I had the same issue but changing the startup to using java 8 solved it

**Comment by ImCoolio** [comment] 2023-03-09 08:54
> looks like java 11 "Java Version: 11.0.18, Debian" try java 8 since its 1.16.5
> 
> I had the same issue but changing the startup to using java 8 solved it

It's not that. My friend was using a compatible version of Java and it still wouldn't let him join, likewise with me on Xubuntu Linux. It's just the BetterDefaultBiomes file having a space in it causing some issues in the modlist crosschecking with the client.

**Comment by DoctorMage** [comment] 2023-03-09 15:13
@Rezondes https://github.com/dr3ams/Roguelike-Adventures-and-Dungeons-2/issues/58

**Comment by bashbers** [comment] 2023-03-10 14:28
Im running a clean install of 1.1 but get the same errors as above. I've tried using JDK8_212, both on Alpine and ubuntu but after reading further into error I found this thread: https://github.com/CreativeMD/ItemPhysicLite/issues/7#issuecomment-952679473
It seems like the server pack has **Item Physics Lite** and is trying to load it serverside which causes the error.

After excluding **ItemPhysicsLite** I ran into **Oculus**, another clientside only mod which gave a similar error. Here is a thread: https://github.com/Asek3/Oculus/issues/279#issuecomment-1398434877

Same for **ItemBorders**: https://www.curseforge.com/minecraft/mc-mods/item-borders
And the same for **legendarytooltips** https://www.curseforge.com/minecraft/mc-mods/legendary-tooltips
And the same for **CraftPresence**: https://www.curseforge.com/minecraft/mc-mods/craftpresence
And the same for **BetterF3** https://www.curseforge.com/minecraft/mc-mods/betterf3

After removing these clientside mods from the servermods mods folder, the server started working for me.
Here is an exhaustive list of CurseForge ID's for those who are using itzg's docker minecraft server:

```
version: '3'

services:
  minecraft:
    image: itzg/minecraft-server:java8
    container_name: minecraft
    ports:
      - "25565:25565"
    volumes:
      - "./mc:/data"
    environment:
      - EULA=TRUE
      - MEMORY=8G
      - VERSION=1.16.5
      - TYPE=AUTO_CURSEFORGE
      - CF_SLUG=roguelike-adventures-and-dungeons-2
      - CF_FILENAME_MATCHER=-1.1
      - CF_EXCLUDE_MODS=270441,581495,513769,532127,297038,401648
    tty: true
    stdin_open: true
```

**Comment by bashbers** [comment] 2023-03-10 14:33
@DoctorMage Could you remove the abovementioned files from the 1.1 server zip? It looks like the zip is created manually.

**Comment by Yorshka-Vermilion** [comment] 2023-03-10 20:43
When i try to launch server on my windows machine it throws out error in "Project MMO (pmmo)" mod, 

`Crash Report UUID: c9d30b18-ba74-49dc-9610-98bfd1f4b8d3[21:31:43] [main/FATAL] [minecraft/Main]: Failed to start the minecraft server
net.minecraftforge.fml.LoadingFailedException: Loading errors encountered: [
        Project MMO (pmmo) has failed to load correctly
§7java.lang.IncompatibleClassChangeError: Method 'dev.ftb.mods.ftbquests.quest.task.TaskType dev.ftb.mods.ftbquests.quest.task.TaskTypes.register(net.minecraft.util.ResourceLocation, dev.ftb.mods.ftbquests.quest.task.TaskType$Provider, java.util.function.Supplier)' must be InterfaceMethodref constant
]
at net.minecraftforge.fml.ModLoader.waitForTransition(ModLoader.java:255) ~[forge:?] {re:classloading}
[...]
at net.minecraftforge.server.ServerMain.main(ServerMain.java:43) [forge-1.16.5-36.2.39.jar:?] {}`

**Comment by Redeye123** [comment] 2023-03-10 22:43
> When i try to launch server on my windows machine it throws out error in "Project MMO (pmmo)" mod too,
> 
> `Crash Report UUID: c9d30b18-ba74-49dc-9610-98bfd1f4b8d3[21:31:43] [main/FATAL] [minecraft/Main]: Failed to start the minecraft server net.minecraftforge.fml.LoadingFailedException: Loading errors encountered: [ Project MMO (pmmo) has failed to load correctly §7java.lang.IncompatibleClassChangeError: Method 'dev.ftb.mods.ftbquests.quest.task.TaskType dev.ftb.mods.ftbquests.quest.task.TaskTypes.register(net.minecraft.util.ResourceLocation, dev.ftb.mods.ftbquests.quest.task.TaskType$Provider, java.util.function.Supplier)' must be InterfaceMethodref constant ] at net.minecraftforge.fml.ModLoader.waitForTransition(ModLoader.java:255) ~[forge:?] {re:classloading} [...] at net.minecraftforge.server.ServerMain.main(ServerMain.java:43) [forge-1.16.5-36.2.39.jar:?] {}`

Start it up with java 8 this is the exact same error i got

**Comment by DoctorMage** [comment] 2023-03-10 23:00
@Redeye123 send the actual crash report please not snippet of the crash report

**Comment by DoctorMage** [comment] 2023-03-10 23:05
you most likely have another java versio installed https://github.com/dr3ams/Roguelike-Adventures-and-Dungeons-2/issues/58

**Comment by dr3ams** [comment] 2023-03-11 08:36
@bashbers there are no such files in the [serverpack](https://www.curseforge.com/minecraft/modpacks/roguelike-adventures-and-dungeons-2/files/4424399). Are you sure you downloaded the right thing?

**Comment by VanyaBaou** [comment] 2023-03-14 21:54
If you are having separate issues from the original issue in this post, please create your own issue instead.
Also this post is a duplicate of #58, closing.

**Closed by VanyaBaou** 2023-03-14 21:54 UTC
Labels: bug, duplicate, crash
