### ISSUE TITLE
[Bug]: I'm stuck in the nether

### ISSUE THREAD

**Issue by GhostWing404101** [dr3ams/Roguelike-Adventures-and-Dungeons-2#279] opened 2023-04-27 21:39 UTC
### General Info

- [X] I didn't added any mods
- [X] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

ATlauncher

### Modpack version

1.2

### Describe your issue

A bug happened! I found a Portal while mining and didn't know what it was because I entered from below. now I'm stuck in the nether and I'm not able to mine obsidian to get out. I have gathered some from chests and tried to make a portal but it didn't work. 

### Steps to reproduce the issue

Go into the portal

### Additional Information

![2023-04-27_17 20 11](https://user-images.githubusercontent.com/132017036/234994531-5ccfafd2-abf0-42d2-8d2a-7478d7fc68d5.png)
this was taken in creative mode from a copy of the world to figure out what it was.

**Comment by Gunner76th** [comment] 2023-04-27 21:59
@GhostWing404101 This is not a bug with the modpack. You failed to read the Quest book. As this is not an issue this ticket will be closed as this is user error.

**Closed** 2023-04-27 22:25 UTC
Labels: bug
