### ISSUE TITLE
Shaders have no night time as if I have perma night vison [Bug]: 

### ISSUE THREAD

**Issue by Thiccthighs033333** [dr3ams/Roguelike-Adventures-and-Dungeons-2#203] opened 2023-02-16 23:03 UTC
### General Info

- [X] I didn't added any mods
- [X] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [X] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

Curseforge

### Modpack version

1.0a

### Describe your issue

Shaders do not have any darkness or night time and in the pictures for the modpack they have darkness

### Steps to reproduce the issue

Use a shader 

### Additional Information

pack not crashing

**Comment by Thiccthighs033333** [comment] 2023-02-16 23:22
I am using the 1.15.5 version of complimentary shaders

**Comment by VanyaBaou** [comment] 2023-02-16 23:24
Duplicate of https://github.com/dr3ams/Roguelike-Adventures-and-Dungeons-2/issues/96
Remove no nv flash mod
Disable "no_night_vision_flash" in Forgery's feature config

Please follow instructions and don't check every box for no reason

**Closed by VanyaBaou** 2023-02-16 23:24 UTC
Labels: bug, duplicate, Low Priority
