### ISSUE TITLE
[Bug]: Glyph press crashes game

### ISSUE THREAD

**Issue by whiteshadow1024** [dr3ams/Roguelike-Adventures-and-Dungeons-2#41] opened 2022-10-30 04:36 UTC
### General Info

- [X] I didn't added any mods
- [ ] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [ ] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

CurseForge

### Modpack version

.6

### Describe your issue

When you are using Ars Nouveau the glyph press will crash your game whenever you go to make a new glyph.

### Steps to reproduce the issue

Place items into glyph press, crash.

### Additional Information

None

**Comment by dr3ams** [comment] 2022-10-30 11:30
**Please provide latest.log located in your logs folder.**
Duplicate of #36

**Closed** 2022-12-05 16:10 UTC
Labels: bug
