### ISSUE TITLE
[Bug]: crash report

### ISSUE THREAD

**Issue by ILove07Gold** [dr3ams/Roguelike-Adventures-and-Dungeons-2#107] opened 2022-12-22 03:53 UTC
### General Info

- [X] I didn't added any mods
- [ ] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [X] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

curseforge

### Modpack version

0.9 (latest)

### Describe your issue

A bug happened! crashed

### Additional Information

[crash-2022-12-21_19.51.30-server.txt](https://github.com/dr3ams/Roguelike-Adventures-and-Dungeons-2/files/10283592/crash-2022-12-21_19.51.30-server.txt)

[latest.log](https://github.com/dr3ams/Roguelike-Adventures-and-Dungeons-2/files/10283598/latest.log)

**Comment by wasdspace** [comment] 2022-12-22 06:37
Duplicate with https://github.com/Shadows-of-Fire/Apotheosis/issues/732

**Comment by VanyaBaou** [comment] 2022-12-24 01:08
Please properly follow instructions when submitting an issue
Closing duplicate of https://github.com/dr3ams/Roguelike-Adventures-and-Dungeons-2/issues/82

**Closed by VanyaBaou** 2022-12-24 01:08 UTC
Labels: bug, crash
