### ISSUE TITLE
[Bug]: Server crashes after "refreshing"

### ISSUE THREAD

**Issue by 9hrt** [dr3ams/Roguelike-Adventures-and-Dungeons-2#234] opened 2023-03-22 19:16 UTC
### General Info

- [ ] I didn't added any mods
- [ ] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [X] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

Curseforge

### Modpack version

1.1

### Describe your issue

server is crashing immediately after launch.

### Steps to reproduce the issue

im turning my server on its loading everything's good and its crashing immediately when im trying to refresh.

### Additional Information

latest log. https://pastebin.com/gwkvvx5v    crash-reports https://pastebin.com/m2rHzXz2

**Comment by DoctorMage** [comment] 2023-03-24 09:35
is this a provider or self hosting

**Comment by VanyaBaou** [comment] 2023-03-24 18:10
@9hrt  Upload your latest.log and crash report directly as files. Some people can't access paste sites like those, and if the paste expires people looking at this lose information.
And you **have** to check either one of the check boxes for it being in single-player or multi-player.

**Comment by VanyaBaou** [comment] 2023-03-24 18:14
And this is a duplicate of https://github.com/dr3ams/Roguelike-Adventures-and-Dungeons-2/issues/228

**Closed by VanyaBaou** 2023-03-24 18:14 UTC
Labels: bug, crash, Need Info
