### ISSUE TITLE
[Bug / Crash Report]: Enchanting and Repairing with Anvils causing a Server Crash

### ISSUE THREAD

**Issue by Hexiphix** [dr3ams/Roguelike-Adventures-and-Dungeons-2#190] opened 2023-02-10 07:26 UTC
### General Info

- [X] I didn't added any mods
- [ ] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [X] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

CurseForge

### Modpack version

1.0a

### Describe your issue

There seems to be an issue, where whenever an anvil is used to either repair gear, or add an enchantment in multiplayer, the server crashes. I am not an expert when it comes to this, but the logs and server console seem to make mention of apotheosis a lot during the crash, so that might be the culprit.

### Steps to reproduce the issue

(1) Join a server running the mod pack
(2) Set down an anvil, get a piece of gear (I used an iron helmet in my test), and an enchantment book (I used unbreaking 3 in my test)
(3) Put the helmet in the anvil
(4) Put the enchantment in the anvil, which will be followed immediately by a server crash

### Additional Information

This was done using a Shockbyte server.

[crash-2023-02-10_06.59.44-server.txt](https://github.com/dr3ams/Roguelike-Adventures-and-Dungeons-2/files/10704631/crash-2023-02-10_06.59.44-server.txt)

[2023-02-10 text from server console after using anvil before stop message.txt](https://github.com/dr3ams/Roguelike-Adventures-and-Dungeons-2/files/10704683/2023-02-10.text.from.server.console.after.using.anvil.before.stop.message.txt)

**Comment by DoctorMage** [comment] 2023-02-10 11:59
is this a clean server setup? as in compleletly new everything

**Comment by Hexiphix** [comment] 2023-02-10 15:54
This is a server that has I've cycled through modpacks a few times at this point. I installed the modpack through Shockbytes version manager and assumed it would automatically clean out any files from the previous modpacks. Let me try and remove any files not relating to user data or world data, and try reinstalling the modpack through the version controller, and test if that changes things.

**Comment by ManuelKahle** [comment] 2023-02-10 20:57
Same here with exact the same crash report :/

**Comment by DoctorMage** [comment] 2023-02-10 22:12
what modpack version are you playing on

**Comment by Hexiphix** [comment] 2023-02-10 23:47
After deleting all the files within the server that were in the CurseForge Server Pack and replacing them with what was in the CurseForge Server Pack through FTP File Access, and changing over to a custom.jar, I can confirm that it seems to have something to do with the version of the modpack that was uploaded to the Server Type section of Shockbyte. Enchanting now seems to work fine after trying this. Might also just be due to a version conflict, as the server version available on ShockByte is actually 1.0, while the version pulled directly from CurseForge is 1.0a. Sorry for the confusion, before closing the report however, please check with ManuelKahle, and see if they ended up with this problem due to the same mix up, or if their circumstances are different.

**Comment by HittingJH** [comment] 2023-02-11 02:50
I am having the same issue from downloading it from cursedforge, I tried adding pages to my buddy binder and my server completely crashed and I am on the latest version 1.0a and I've redownloaded the pack to make sure I didn't have any corrupt files and still having the same issue

[crash-2023-02-10_21.44.00-server.txt](https://github.com/dr3ams/Roguelike-Adventures-and-Dungeons-2/files/10712403/crash-2023-02-10_21.44.00-server.txt)

**Comment by ManuelKahle** [comment] 2023-02-11 10:06
@DoctorMage 
I am using the Version "1.0a"

Also tried on a clean setup, still not working

**Comment by DoctorMage** [comment] 2023-02-11 11:00
what were you trying to enchant

**Comment by DoctorMage** [comment] 2023-02-11 11:02
Because i'm unable to recreate any crash with interacting with anvil and enchanting in 2 different servers and multiple singleplayer worlds

**Comment by DoctorMage** [comment] 2023-02-11 11:18
If you wish to use an older world oyu must remove the mod forgery
seems to be causing issues
this has to be removed both server and client side

**Comment by ManuelKahle** [comment] 2023-02-11 11:53
Jup that was the cause, thank you.

btw this Modpack is insane!

**Comment by DoctorMage** [comment] 2023-02-11 18:44
@Hexiphix figured it out shockbyte is still using some older configs 
![image](https://user-images.githubusercontent.com/85318453/218275552-167d7bb4-164c-444a-a675-1fe96eb4d83a.png)
shockbytes one
vs
1.0a servers one 
![image](https://user-images.githubusercontent.com/85318453/218275581-6c7294b1-50ee-4c23-a7ac-3ab6f80c966e.png)

**Comment by SFort** [comment] 2023-02-13 00:47
Fixed in forgery 3.1.8, my fuckup as i tested on j11 while 1.16 uses 8.
Please submit issues upstream or ping me(not sure if that's even a fetarue in github), it was a miracle i was linked this.

**Comment by DoctorMage** [comment] 2023-02-13 11:18
Completelty slipped my mind to report it to the mod author assumed it was something on our end

**Comment by Hexiphix** [comment] 2023-02-13 21:56
@DoctorMage I think SFort already indicated that they made the fix in version 3.1.8. I don't know if whoever uploads the Server Types to ShockByte ended up seeing this, or if just anyone is able to change those, but it looks like that may have been updated, however I do have things working on my end with the 1.0a version after handling things more directly through CurseForge, and uploading that to the server instead. Is everything also already cleared up for ManuelKahle and HittingJH, cause if so then the issue might be ready to close.

**Closed** 2023-02-13 21:58 UTC
Labels: bug, Fix Incoming
