### ISSUE TITLE
[Bug]: Wither crashes my server

### ISSUE THREAD

**Issue by clytemnestra** [dr3ams/Roguelike-Adventures-and-Dungeons-2#304] opened 2023-05-22 17:50 UTC
### General Info

- [ ] I didn't added any mods
- [ ] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [X] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

Curseforge

### Modpack version (Do not say latest check curseforge has it on modpacks icon)

1.3

### Describe your issue

I am spawning the wither in the overworld and it crashes my server after a minute or two of fighting it. Happened 3 times in a row and one time yesterday

### Steps to reproduce the issue
Spawned wither at night and after fighting it for 1-2 minutes my server crashes

_No response_

### Additional Information
Provided logs for one of the crashes as they are the same.
[new 2.txt](https://github.com/dr3ams/Roguelike-Adventures-and-Dungeons-2/files/11534590/new.2.txt)

First two withers got removed by the server automatically. The third stayed and crashed it 3 times before I could finally reconnect and kill it. One instance I managed to log in for 2 seconds and it crashed the server instantly

**Comment by DoctorMage** [comment] 2023-05-23 08:37
caused by wither minion for now go to progressive bosses config
and turn them false

**Comment by DoctorMage** [comment] 2023-05-23 08:52
not wither wither minion

**Comment by DoctorMage** [comment] 2023-05-23 08:52
![image](https://github.com/dr3ams/Roguelike-Adventures-and-Dungeons-2/assets/85318453/7ab3c56b-25ae-45bf-bdfc-0654b0d30574)

**Comment by DoctorMage** [comment] 2023-05-23 08:54
will be disabled next update

**Comment by DoctorMage** [comment] 2023-05-23 08:54
oversight that it lasted so long

**Comment by DoctorMage** [comment] 2023-05-23 08:58
changing one line from true to false so no literally just done it so now just need to wait for next modpack update

**Comment by DoctorMage** [comment] 2023-06-22 19:34
fixed in 1.4a

**Closed by DoctorMage** 2023-06-22 19:34 UTC
Labels: bug, Known Issue
